### ISSUE TITLE
about traffic light

### ISSUE THREAD

**Issue by LetStarFly** [ai4ce/V2X-Sim#1]
I have tow question. 
Did you add the traffic lights in the map by yourself? How should it be added? 
The second is that I see that you put sensors in the air. How is this achieved ?
Thanks~

**Comment by ziyanan** [comment]
We used the default traffic lights in CARLA maps. However, they do provide ([customization options](https://carla.readthedocs.io/en/latest/tuto_M_custom_add_tl/#traffic-lights)) so you can add your own traffic lights.

The sensors at the intersections are attached to traffic lights. Specifically, you can use the method in CARLA Python API: `camera = world.spawn_actor(camera_bp, relative_transform, attach_to=my_vehicle)` with `attach_to` equals to a traffic light of your choice. Here's an example of how you can spawn a sensor: [link](https://carla.readthedocs.io/en/latest/core_actors/#sensors).
