### ISSUE TITLE
coperception codebase

### ISSUE THREAD

**Issue by simbaforrest** [ai4ce/V2X-Sim#3]
Should we use git submodules to include the coperception library in V2X-Sim? @dekunma

**Comment by dekunma** [comment]
I have discussed this with @RoboticsYimingLi, and we think that it might be better to leave the code base this way for the best reproducibility of our paper.

**Comment by simbaforrest** [comment]
@dekunma are you worried about future changes in co-perception library? If so, you don't have to worry because submodules can specify which commit of the repo you are referencing, so it is in fact the same, unless the current coperception folder is different than the library (which should not happen because all the changes should happen inside the library repo).

**Comment by dekunma** [comment]
That makes a lot of sense. I have done so in the latest commit. Thank you!
