### ISSUE TITLE
question of pcd file

### ISSUE THREAD

**Issue by zjr-bit** [ai4ce/V2X-Sim#6]
Hi，thanks for your great work!
I have one question: what is the information in .pcd.bin file? 
The x,y,z of point and other information?
In other words, how many fields of one point?
Looking forward to your reply, Thanks!

**Comment by zjr-bit** [comment]
And I want load the .pcd.bin file in the below way:
`np.fromfile(pcd_path, dtype=np.float32)`
Is it right?
Or could you please tell me a better way?

**Comment by zjr-bit** [comment]
And what is the coordinate of .pcd file? 
Look forward to your reply, Thanks!

**Comment by dekunma** [comment]
Hi @zjr-bit, the `.pcd.bin` files contain point cloud information captured by LiDAR sensors. For example, the files in `LIDAR_TOP_id_0` contain point cloud captured by the top lidar of agent 0.  
To read the point cloud data from such files, I would recommend doing something like this:
```python
from nuscenes.utils.data_classes import LidarPointCloud

path_to_pcd = './V2X-Sim-2.0-mini/sweeps/LIDAR_TOP_id_0/scene_5_000006.pcd.bin'
pc = LidarPointCloud.from_file(path_to_pcd)
pc.points.T.shape #(24504, 4)
```
The point cloud is a shape of N x 4 (where N is the number of points in the point cloud), and the four dimensions are x, y, z and intensity.

**Comment by zjr-bit** [comment]
Thanks for your reply!
And so the coordinate is the lidar sensor?

**Comment by dekunma** [comment]
It depends on which directory the `.pcd.bin` file locates. For example, if it is in `LIDAR_TOP_id_*` then it corresponds to the top lidar sensor.

**Comment by dekunma** [comment]
Yes, I think so
