### ISSUE TITLE
about v2.0

### ISSUE THREAD

**Issue by zjr-bit** [ai4ce/V2X-Sim#7]
Hi!
I'm trying to load the V2XSim. I have downloaded the sensor I need, but I could't find the *.json files of v2.0, just like the files of v2.0-mini. Could you please tell me where to find them? Thanks!!!

**Comment by dekunma** [comment]
The metadata (.json files) of v2.0 is located at: https://drive.google.com/drive/folders/1nVmY7g_kprOX-I0Bqsiz6-zdJM-UXFXa
in the `v1.0-mini.zip` file. (Yes, it is for v2.0, and it should have been named as `v2.0.zip`. We will fix this shortly.)
![image](https://user-images.githubusercontent.com/53892579/210904461-555ca151-9bb3-4e94-ba2b-733d71d4436f.png)

**Comment by zjr-bit** [comment]
Thank you! I got it!
